export * from './home/home.component';
export * from  './user/user.component';
export * from './logout/logout.component';
export * from './links/link.component';
export * from './demo/demo.component';
export * from './democ/democ.component';
export * from './demod/demod.component';
export * from './chat/chat.component';
export * from './autoform/autoform.component';
